// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Connect4Challenge.Runtime")>]
[<assembly: AssemblyProductAttribute("Connect4Challenge")>]
[<assembly: AssemblyDescriptionAttribute("Connect4 programming challenge.")>]
[<assembly: AssemblyVersionAttribute("0.0.2")>]
[<assembly: AssemblyFileVersionAttribute("0.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Connect4Challenge.Runtime"
    let [<Literal>] AssemblyProduct = "Connect4Challenge"
    let [<Literal>] AssemblyDescription = "Connect4 programming challenge."
    let [<Literal>] AssemblyVersion = "0.0.2"
    let [<Literal>] AssemblyFileVersion = "0.0.2"
