// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Connect4Challenge.Web")]
[assembly: AssemblyProductAttribute("Connect4Challenge")]
[assembly: AssemblyDescriptionAttribute("Connect4 programming challenge.")]
[assembly: AssemblyVersionAttribute("0.0.2")]
[assembly: AssemblyFileVersionAttribute("0.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.2";
    }
}
