// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Connect4Challenge.Bot")]
[assembly: AssemblyProductAttribute("Connect4Challenge")]
[assembly: AssemblyDescriptionAttribute("Connect4Challenge is a programming challenge. You can compete against our algorithm by implementing the ConnectFour Interface. You can wirte you Code in F# or C#.")]
[assembly: AssemblyVersionAttribute("0.0.2")]
[assembly: AssemblyFileVersionAttribute("0.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.0.2";
    }
}
