// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Connect4Challenge.Bot")]
[assembly: AssemblyProductAttribute("Connect4Challenge")]
[assembly: AssemblyDescriptionAttribute("Connect4 programming challenge.")]
[assembly: AssemblyVersionAttribute("0.0.2")]
[assembly: AssemblyFileVersionAttribute("0.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Connect4Challenge.Bot";
        internal const System.String AssemblyProduct = "Connect4Challenge";
        internal const System.String AssemblyDescription = "Connect4 programming challenge.";
        internal const System.String AssemblyVersion = "0.0.2";
        internal const System.String AssemblyFileVersion = "0.0.2";
    }
}
